# ANÁLISIS DE LA BASE DE DATOS BCCC-CIC-IDS-2017

In [1]:
import pandas as pd
import glob
import os

directorio_actual = os.getcwd()
nombre_dataset = "BCCC17"
directorio_dataset = os.path.abspath(
    os.path.join(directorio_actual, "../../../02_datasets/raw", nombre_dataset)
)

archivos = glob.glob(directorio_dataset + "/*.csv")
archivos.sort()

df_list = []

for archivo in archivos:
    print(f"Leyendo: {archivo}")
    df_temp = pd.read_csv(archivo, low_memory=False)
    df_list.append(df_temp)

df = pd.concat(df_list, ignore_index=True)

Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/botnet_ares.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/ddos_loit.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/dos_golden_eye.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/dos_hulk.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/dos_slowhttptest.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/dos_slowloris.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/friday_benign.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/ftp_patator.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/heartbleed.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/monday_benign.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/portscan.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/ssh_patator-new.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/thursday_benign.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/tuesday_benign.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/web_brute_force.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/web_sql_injection.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/web_xss.csv
Leyendo: /home/ana/Documentos/TFG/02_datasets/raw/BCCC17/wednesday_benign.csv

## Lista con todos los atributos

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2438052 entries, 0 to 2438051
Columns: 122 entries, flow_id to label
dtypes: float64(61), int64(55), str(6)
memory usage: 2.5 GB

## Primeros elementos de la base de datos

In [3]:
df.head()

,flow_id,timestamp,src_ip,src_port,dst_ip,dst_port,protocol,duration,packets_count,fwd_packets_count,...,bwd_packets_IAT_mean,bwd_packets_IAT_std,bwd_packets_IAT_max,bwd_packets_IAT_min,bwd_packets_IAT_total,subflow_fwd_packets,subflow_bwd_packets,subflow_fwd_bytes,subflow_bwd_bytes,label
0,192.168.10.9_1841_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:13.990571,192.168.10.9,1841,205.174.165.73,8080,TCP,0.135358,8,4,...,0.044844,0.061008,0.131123,0.001660,0.134532,0.0,0.0,0.0,0.0,Botnet_ARES
1,192.168.10.9_1845_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:24.131090,192.168.10.9,1845,205.174.165.73,8080,TCP,0.128585,8,4,...,0.042638,0.057734,0.124286,0.001701,0.127915,0.0,0.0,0.0,0.0,Botnet_ARES
2,192.168.10.9_1846_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:34.262355,192.168.10.9,1846,205.174.165.73,8080,TCP,0.166355,10,5,...,0.041467,0.070571,0.163697,0.000204,0.165869,0.0,0.0,0.0,0.0,Botnet_ARES
3,192.168.10.9_1847_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:34.526581,192.168.10.9,1847,205.174.165.73,8080,TCP,0.065549,8,4,...,0.021602,0.028732,0.062233,0.001017,0.064805,0.0,0.0,0.0,0.0,Botnet_ARES
4,192.168.10.9_1848_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:44.594895,192.168.10.9,1848,205.174.165.73,8080,TCP,0.080872,8,4,...,0.026761,0.036088,0.077792,0.000637,0.080284,0.0,0.0,0.0,0.0,Botnet_ARES

## Número de elementos por etiqueta

In [4]:
df["label"].value_counts()

label
Benign               1786239
DoS_Hulk              349240
Port_Scan             161323
DDoS_LOIT              95733
FTP-Patator             9531
DoS_GoldenEye           8364
DoS_Slowhttptest        6860
SSH-Patator             5949
Botnet_ARES             5508
DoS_Slowloris           5177
Web_Brute_Force         2734
Web_XSS                 1358
Web_SQL_Injection         24
Heartbleed                12
Name: count, dtype: int64

In [5]:
df.shape

(2438052, 122)

In [6]:
df.dtypes

flow_id                    str
timestamp                  str
src_ip                     str
src_port                 int64
dst_ip                     str
                        ...
subflow_fwd_packets    float64
subflow_bwd_packets    float64
subflow_fwd_bytes      float64
subflow_bwd_bytes      float64
label                      str
Length: 122, dtype: object

In [7]:
df["label"].value_counts(normalize=True)

label
Benign               0.732650
DoS_Hulk             0.143246
Port_Scan            0.066169
DDoS_LOIT            0.039266
FTP-Patator          0.003909
DoS_GoldenEye        0.003431
DoS_Slowhttptest     0.002814
SSH-Patator          0.002440
Botnet_ARES          0.002259
DoS_Slowloris        0.002123
Web_Brute_Force      0.001121
Web_XSS              0.000557
Web_SQL_Injection    0.000010
Heartbleed           0.000005
Name: proportion, dtype: float64

In [8]:
################## COLUMNAS CON VALORES ÚNICOS #####################
df.nunique().sort_values().head(20)

urg_flag_counts          1
bwd_urg_flag_counts      1
fwd_urg_flag_counts      1
protocol                 2
rst_flag_counts          2
bwd_ece_flag_counts      2
bwd_rst_flag_counts      2
fwd_rst_flag_counts      2
fwd_ece_flag_counts      2
ece_flag_counts          3
bwd_cwr_flag_counts      4
min_header_bytes         7
fwd_cwr_flag_counts      8
bwd_fin_flag_counts      8
fwd_min_header_bytes     8
bwd_min_header_bytes     9
cwr_flag_counts          9
max_header_bytes        11
bwd_max_header_bytes    11
bwd_syn_flag_counts     12
dtype: int64

In [9]:
################## COLUMNAS CON ALTA CORRELACIÓN #####################
import numpy as np
import pandas as pd

df_datos = df.drop(columns="label")

# Solo columnas numéricas
df_num = df_datos.select_dtypes(include=np.number)

corr_matrix = df_num.corr().abs()

high_corr = (
    corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    .stack()
    .sort_values(ascending=False)
)

high_corr[high_corr > 0.95].shape

(158,)

In [10]:
#################### FILAS CON VALORES INFINITO, VACÍO Y NULO ###################
# Filas con valores nulos
df[df.isnull().any(axis=1)].shape

(0, 122)

In [11]:
# Filas con valores infinito
df_num[np.isinf(df_num).any(axis=1)].shape

(0, 116)

In [12]:
df.select_dtypes(include="object").columns

/tmp/ipykernel_20934/1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['flow_id', 'timestamp', 'src_ip', 'dst_ip', 'protocol', 'label'], dtype='str')

In [13]:
df['flow_id'].head()

0    192.168.10.9_1841_205.174.165.73_8080_TCP_2017...
1    192.168.10.9_1845_205.174.165.73_8080_TCP_2017...
2    192.168.10.9_1846_205.174.165.73_8080_TCP_2017...
3    192.168.10.9_1847_205.174.165.73_8080_TCP_2017...
4    192.168.10.9_1848_205.174.165.73_8080_TCP_2017...
Name: flow_id, dtype: str

In [14]:
df.head()

,flow_id,timestamp,src_ip,src_port,dst_ip,dst_port,protocol,duration,packets_count,fwd_packets_count,...,bwd_packets_IAT_mean,bwd_packets_IAT_std,bwd_packets_IAT_max,bwd_packets_IAT_min,bwd_packets_IAT_total,subflow_fwd_packets,subflow_bwd_packets,subflow_fwd_bytes,subflow_bwd_bytes,label
0,192.168.10.9_1841_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:13.990571,192.168.10.9,1841,205.174.165.73,8080,TCP,0.135358,8,4,...,0.044844,0.061008,0.131123,0.001660,0.134532,0.0,0.0,0.0,0.0,Botnet_ARES
1,192.168.10.9_1845_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:24.131090,192.168.10.9,1845,205.174.165.73,8080,TCP,0.128585,8,4,...,0.042638,0.057734,0.124286,0.001701,0.127915,0.0,0.0,0.0,0.0,Botnet_ARES
2,192.168.10.9_1846_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:34.262355,192.168.10.9,1846,205.174.165.73,8080,TCP,0.166355,10,5,...,0.041467,0.070571,0.163697,0.000204,0.165869,0.0,0.0,0.0,0.0,Botnet_ARES
3,192.168.10.9_1847_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:34.526581,192.168.10.9,1847,205.174.165.73,8080,TCP,0.065549,8,4,...,0.021602,0.028732,0.062233,0.001017,0.064805,0.0,0.0,0.0,0.0,Botnet_ARES
4,192.168.10.9_1848_205.174.165.73_8080_TCP_2017...,2017-07-07 09:04:44.594895,192.168.10.9,1848,205.174.165.73,8080,TCP,0.080872,8,4,...,0.026761,0.036088,0.077792,0.000637,0.080284,0.0,0.0,0.0,0.0,Botnet_ARES

In [15]:
list(df.columns)

['flow_id',
 'timestamp',
 'src_ip',
 'src_port',
 'dst_ip',
 'dst_port',
 'protocol',
 'duration',
 'packets_count',
 'fwd_packets_count',
 'bwd_packets_count',
 'total_payload_bytes',
 'fwd_total_payload_bytes',
 'bwd_total_payload_bytes',
 'payload_bytes_max',
 'payload_bytes_min',
 'payload_bytes_mean',
 'payload_bytes_std',
 'payload_bytes_variance',
 'fwd_payload_bytes_max',
 'fwd_payload_bytes_min',
 'fwd_payload_bytes_mean',
 'fwd_payload_bytes_std',
 'fwd_payload_bytes_variance',
 'bwd_payload_bytes_max',
 'bwd_payload_bytes_min',
 'bwd_payload_bytes_mean',
 'bwd_payload_bytes_std',
 'bwd_payload_bytes_variance',
 'total_header_bytes',
 'max_header_bytes',
 'min_header_bytes',
 'mean_header_bytes',
 'std_header_bytes',
 'fwd_total_header_bytes',
 'fwd_max_header_bytes',
 'fwd_min_header_bytes',
 'fwd_mean_header_bytes',
 'fwd_std_header_bytes',
 'bwd_total_header_bytes',
 'bwd_max_header_bytes',
 'bwd_min_header_bytes',
 'bwd_mean_header_bytes',
 'bwd_std_header_bytes',
 'fwd_avg_segment_size',
 'bwd_avg_segment_size',
 'avg_segment_size',
 'fwd_init_win_bytes',
 'bwd_init_win_bytes',
 'active_min',
 'active_max',
 'active_mean',
 'active_std',
 'idle_min',
 'idle_max',
 'idle_mean',
 'idle_std',
 'bytes_rate',
 'fwd_bytes_rate',
 'bwd_bytes_rate',
 'packets_rate',
 'bwd_packets_rate',
 'fwd_packets_rate',
 'down_up_rate',
 'avg_fwd_bytes_per_bulk',
 'avg_fwd_packets_per_bulk',
 'avg_fwd_bulk_rate',
 'avg_bwd_bytes_per_bulk',
 'avg_bwd_packets_bulk_rate',
 'avg_bwd_bulk_rate',
 'fwd_bulk_state_count',
 'fwd_bulk_total_size',
 'fwd_bulk_per_packet',
 'fwd_bulk_duration',
 'bwd_bulk_state_count',
 'bwd_bulk_total_size',
 'bwd_bulk_per_packet',
 'bwd_bulk_duration',
 'fin_flag_counts',
 'psh_flag_counts',
 'urg_flag_counts',
 'ece_flag_counts',
 'syn_flag_counts',
 'ack_flag_counts',
 'cwr_flag_counts',
 'rst_flag_counts',
 'fwd_fin_flag_counts',
 'fwd_psh_flag_counts',
 'fwd_urg_flag_counts',
 'fwd_ece_flag_counts',
 'fwd_syn_flag_counts',
 'fwd_ack_flag_counts',
 'fwd_cwr_flag_counts',
 'fwd_rst_flag_counts',
 'bwd_fin_flag_counts',
 'bwd_psh_flag_counts',
 'bwd_urg_flag_counts',
 'bwd_ece_flag_counts',
 'bwd_syn_flag_counts',
 'bwd_ack_flag_counts',
 'bwd_cwr_flag_counts',
 'bwd_rst_flag_counts',
 'packets_IAT_mean',
 'packet_IAT_std',
 'packet_IAT_max',
 'packet_IAT_min',
 'packet_IAT_total',
 'fwd_packets_IAT_mean',
 'fwd_packets_IAT_std',
 'fwd_packets_IAT_max',
 'fwd_packets_IAT_min',
 'fwd_packets_IAT_total',
 'bwd_packets_IAT_mean',
 'bwd_packets_IAT_std',
 'bwd_packets_IAT_max',
 'bwd_packets_IAT_min',
 'bwd_packets_IAT_total',
 'subflow_fwd_packets',
 'subflow_bwd_packets',
 'subflow_fwd_bytes',
 'subflow_bwd_bytes',
 'label']