In [1]:
from pathlib import Path
import re
from os import listdir
import pandas as pd

In [2]:
k = 3
BASE_DIR = Path("../../../").resolve()
ruta_base_dataset = str(BASE_DIR / "02_datasets" / "processed" / "pd_BCCC17__RUS_SMOTE_ENN__v1")
model_path = str(BASE_DIR / "04_experimentos" / "modelos" / "t5-small")
output_path = str(BASE_DIR / "04_experimentos" / "modelos" / "pd_BCCC17__RUS_SMOTE_ENN__v1__outputs" / f"pd_BCCC17__RUS_SMOTE_ENN__v1__outputs__{k}_5")

nombre_train = f"pd_BCCC17__RUS_SMOTE_ENN__v1__train__{k}.csv"
nombre_val = f"pd_BCCC17__RUS_SMOTE_ENN__v1__val__{k}.csv"

In [3]:
import sys
sys.path.append("../../utils/")

from utils import *

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/cuda/__init__.py:180: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0

In [4]:
df_train = cargar_dataset(nombre_train, ruta_base_dataset)
df_val = cargar_dataset(nombre_val, ruta_base_dataset)

df_train['source_text'] = df_train['source_text'].astype(str)
df_train['target_text'] = df_train['target_text'].astype(str)
df_val['source_text'] = df_val['source_text'].astype(str)
df_val['target_text'] = df_val['target_text'].astype(str)

In [5]:
df_train.head()

                                         source_text target_text
0  2107730|42690|0|0.0|1|0|0|0|0.0|0.0|0.0|32|32|...           0
1  2396259|443|0|0.363271951675415|29|789|2920|0|...           0
2  1233089|53|1|0.0001718997955322|4|72|68|36|52....           0
3  994256|53|1|0.0483229160308837|4|86|85|43|64.0...           0
4  1267994|50961|0|0.0|1|0|0|0|0.0|0.0|0.0|32|32|...           0

In [6]:
model_train_data = SimpleT5Wrapper()
model_train_data.from_pretrained("t5", model_path, use_gpu=True)

Loading weights:   0%|          | 0/134 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

The tied weights mapping and config for this model specifies to tie shared.weight to encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

The tied weights mapping and config for this model specifies to tie shared.weight to decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

In [7]:
model_train_data.train(
    train_df=df_train,
    eval_df=df_val,
    source_max_token_len=150,
    target_max_token_len=3,
    batch_size=16,
    precision=32,
    max_epochs=10,
    outputdir=output_path,
    use_gpu=True,
    dataloader_num_workers=16
)

Map:   0%|          | 0/110849 [00:00<?, ? examples/s]

Map:   0%|          | 0/27712 [00:00<?, ? examples/s]

[RANK 0] Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/home/inginf/u32902122/.conda/envs/tfgClean/lib/python3.11/site-packages/torch/utils/data/dataloader.py:1118: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['encoder.embed_tokens.weight', 'decoder.embed_tokens.weight', 'lm_head.weight'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]